### ISSUE TITLE
Something wrong with two shortcuts

### ISSUE THREAD

**Issue by minisauruslepro** [capasha/EEditor-#10]
CTRL+Z does not work at all (CTRL+Y works)
B for spray is incorrect (V works for it)
Not sure if there is other shortcuts that are currently not working, I know only those two.

I wonder if there is a file to apply customized shortcuts

**Comment by capasha** [comment]
Do you use another keyboard? I could add customized shortcuts.

**Comment by minisauruslepro** [comment]
Custom shortcuts might help
Also I struggle with switching from block to block, a way to have shortcut keys for 0-9 in keyboard to add items like in EE would help to build in EEditor much faster (and a blockpicker key while pressing the number would help too)

**Comment by capasha** [comment]
It's changed to V now, and not B on the tooltip.
The other thing you requested already exists.

**Hold 0 - 9 + click on a block - Bind a block to held key**

You are going to see numbers on each block in the block menu when you have done this.

**Comment by capasha** [comment]
Since this is not about blockpicker I wonder does ctrl + z still use ctrl + y?

**Comment by capasha** [comment]
This is now fixed.
