### ISSUE TITLE
Two things wrong with find&replace portal feature

### ISSUE THREAD

**Issue by minisauruslepro** [capasha/EEditor-#7]
1° The "Click on the portal icon to change rotation" does not work, it keeps in rotation 0
![image](https://user-images.githubusercontent.com/39227035/91894706-1d427200-ec64-11ea-9f4f-3d946ea4bc0a.png)

2° The replace next&replace all simple deletes all portals in the world for blues and does nothing for gray protals

Version: 5.0.8 and 5.0.9 (not sure if even more previous versions had this issue)

**Comment by capasha** [comment]
Thanks for reporting. It's fixed now.
