### ISSUE TITLE
Something wrong with default portal ID placement

### ISSUE THREAD

**Issue by minisauruslepro** [capasha/EEditor-#9]
The default portal ID placement places either 1/1 or 0/0 randomly, this varies depending on the tool used, fill tool, spray tool, pencil tool, etc
(It should be as default always 0/0)
For example spray tool sprays randomly either 1/1 or 0/0 when it has the default portal ID (Not yet user defined)
After you set defined value the portals places the correct IDs
Version: 5.0.8 and 5.0.9 (not sure if even more previous versions had this issue)

**Comment by capasha** [comment]
Thanks for the report, everything should now be fixed.
